name: CI
run-name: ${{ github.job }} commit ${{ github.sha }} is running GitHub Actions 🚀


on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - master


jobs:
  Set_Output:
    runs-on: ubuntu-latest
    steps:
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out to my repo
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.2.1

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16
          cache: pnpm

      - name: Setup
        run: pnpm install

      - name: Lint
        run: pnpm lint:js

      - name: Type Checking
        run: pnpm tsc

      - name: Build
        run: pnpm vite build
  Type_Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out to my repo
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.2.1

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16
          cache: pnpm

      - name: Setup
        run: pnpm install

      - name: Type Checking
        run: pnpm tsc

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out to my repo
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.2.1

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16
          cache: pnpm

      - name: Setup
        run: pnpm install

      - name: Build
        run: pnpm vite build
