name: CI
run-name: ${{ github.actor }} is running GitHub Actions 🚀
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: pnpm install
      - run: pnpm lint:js
      - run: build
